apm-lambda-extension/cli/install.js
This fixes a bug in the installer's chip architecture detector. 
Amazon uses the following abbreviations for ARM/Intel: `arm64`, `x86_64`
Go's build tools use the following abbreviations for ARM/Intel: `arm64`, `amd64`
This PR make sure that we're setting the correct value when building the extension with the installer.
=> fix: use "amd64" string for intel-compat builds (amazon uses x86_64)

apm-lambda-extension/extension/apm_server.go, apm-lambda-extension/extension/apm_server_test.go, apm-lambda-extension/extension/process_events.go, apm-lambda-extension/main.go
Instead of using `io.Copy`, use a more straightforward compression approach. Also use a buffer pool to avoid creating a new buffer each time a request is sent.
=> Use more straightforward compression approach and buffer pool

apm-lambda-extension/extension/http_server.go, apm-lambda-extension/extension/http_server_test.go, apm-lambda-extension/extension/process_events.go, apm-lambda-extension/extension/route_handlers.go, apm-lambda-extension/main.go
While working on #62, I found that it was awkward to find a way to pass the channel signaling that the function completed to the router handler. In defining the handlers as they are in this PR, we can easily pass the channel to the handler function, without having to keep a reference to it somewhere.
=> Refactor route handling and server

apm-lambda-extension/extension/http_server.go
I unintentionally removed the server configurations in a previous PR and I'm opening this PR so we can discuss whether we want these settings to be configurable.
Questions:
I personally think we should provide as few configuration options as possible to the user and only options in later if we need them.
=> Add server configurations back in

docs/aws-lambda-extension.asciidoc
Closes: #69
This PR adds a section to the docs with _an overview of all of the steps required at the start of this guide._.
=> feat: add overview section with main steps

apm-lambda-extension/extension/http_server_test.go, apm-lambda-extension/extension/route_handlers.go
This PR contains these changes:
- Uses copy as per @stuartnelson3's [suggestion](https://github.com/elastic/apm-aws-lambda/pull/78/files#r753004695) to forward the apm server's info response back to the agent
- It adds an intake test and a test that the extension forwards an error from an info request
- Removes a check that the body is nil, as the documentation says it won't ever be nil
=> Use copy for info response and add intake test

apm-lambda-extension/extension/http_server_test.go, apm-lambda-extension/extension/route_handlers.go, apm-lambda-extension/main.go
This PR adds a change to signal on a channel when it receives an intake request from an agent containing the query param "flushed=true".
We can change the name of the query param, if that's not clear enough.
As a fallback, it also signals if it receives a `runtimeDone` event from the logsapi.
There are now three channels used to signal in main. The `AgentDoneSignal` signals that there was an intake request received with `flushed=true`, the `runtimeDoneSignal` channel signals that a runtimeDone event was received via the Logs API. The `funcDone` channel is closed if a signal is received on `AgentDoneSignal` or `runtimeDoneSignal`.
Closing that channel signals to the go routines posting apm data and processing logs API events that they can return.
Resolves #62
=> Use query param to intake API to signal that function completed

apm-lambda-extension/cli/.eslintrc.js, apm-lambda-extension/cli/build-and-publish.js, apm-lambda-extension/cli/elastic-lambda.js, apm-lambda-extension/cli/install.js, apm-lambda-extension/cli/package-lock.json, apm-lambda-extension/cli/package.json, apm-lambda-extension/cli/tests/build-and-publish.test.js, apm-lambda-extension/cli/tests/update-layer.test.js, apm-lambda-extension/cli/update-function-env.js, apm-lambda-extension/cli/update-layer.js
Adds eslint to CLI project, adjusts existing code to pass eslint rules.  
I'm not tied to any particular ruleset, (other than a ruleset that is applied by robots ;)), so suggestions for additional entries to `rules:` or even extending something other than `standard` is welcome.
=> feat: add eslint to cli project

docs/aws-lambda-extension.asciidoc
=> Add Java agent section to installation docs

apm-lambda-extension/DEVELOPMENT.md
Adds a `DEVELOPMENT.md` to the repo that includes information on how we're building a release.
=> feat: adds a development doc with the steps for a release

README.md
Now that docs are included in the APM Guide (see https://github.com/elastic/apm-server/pull/6984), we should link to the docs instead of the asciidoc file.
=> Link to built-docs instead of asciidoc file

apm-lambda-extension/extension/process_env.go, apm-lambda-extension/extension/process_env_test.go, apm-lambda-extension/main.go, docs/aws-lambda-extension.asciidoc
=> Allow for different send strategy via environment variable

apm-lambda-extension/extension/http_server_test.go, apm-lambda-extension/extension/route_handlers.go
I've also added a change to only add data to the data channel if the length of the bytes received is > 0.
=> Add test that flushed query param is processed even with empty data

apm-lambda-extension/main.go
Ensure that the go routine finishes sending to the APM server before the extension considers its work done and polls for the next event.
=> Use WaitGroup to ensure go routine finishes sending to APM server

.ci/Jenkinsfile, .ci/create-arn-table.sh, .gitignore, apm-lambda-extension/DEVELOPMENT.md, apm-lambda-extension/Makefile
Publish the AWS lambda as an ARN for AWS users in various regions for `linux` and `arm`.
It happens when a new Git tag is created with the format `v.major.minor.patch` then:
1) Create the binaries for AMD64 and ARM64
2) Publish the AWS lambda in each AWS region
3) Create a release entry in the GitHub UI that includes the ARN for each region and platform and the list of changes.
Refactored the Makefile to avoid duplicated code and added section in the `DEVELOPMENT.md` regarding this new release automation.
1) Delegate all the logic for build/test/distribute and publish in AWS to the Makefile. This should help to run locally the same script, so as long as you have the right permissions then it should work out of the box.
2) CI should only provision workers, configure credentials, checkout …
=> ci: automate ARN publishing

.ci/jobs/apm-aws-lambda-mbp.yml
Run builds in the CI for tag releases
Otherwise the changes in https://github.com/elastic/apm-aws-lambda/pull/101 won't be triggered
=> [jjbb] enable tag releases in Jenkins

apm-lambda-extension/Makefile
Remove CompatibleArchitectures and use the arch in the description instead
```
An error occurred (InvalidParameterValueException) when calling the PublishLayerVersion operation: CompatibleArchitectures are not supported in af-south-1. Please remove the CompatibleArchitectures value from your request and try again
```
=> publish: some regions don't suppport CompatibleArchitectures

.ci/Jenkinsfile
Send email/slack message when a release tag is created and published/failed
Add visibility about the release process
=> ci: notify when a release tag has been created and published

.ci/Jenkinsfile, .ci/create-arn-table.sh, apm-lambda-extension/Makefile
Add debug traces.
Store files generated while publishing the ARN lambda (the output from aws lambda  --output json  publish-layer-version)
Fix a parsing error in the CI that I was not able to reproduce it locally
```
12:29:09  make create-arn-file
12:29:09  make[1]: Entering directory '/var/lib/jenkins/workspace/ibrary_apm-aws-lambda-mbp_v0.0.3/src/github.com/elastic/apm-aws-lambda/apm-lambda-extension'
12:29:09  parse error: Invalid numeric literal at line 1, column 5
```
```bash
AWS_ACCESS_KEY_ID=*** \
AWS_SECRET_ACCESS_KEY=*** \
BRANCH_NAME=v0.0.0.1 \
SUFFIX_ARN_FILE=arn.md \
ELASTIC_LAYER_NAME=v1v-aws-lambda-test \
make publish-in-all-aws-regions
publish 'v1v-aws-lambda-test' in af-south-1
publish 'v1v-aws-lambda-test' in eu-north-1
publish 'v1v-aws-lambda-test' in ap-south-1
publish …
```
=> ci: add info traces to help with debugging

apm-lambda-extension/cli/profile/code/collector.yaml
Remove hard coded APM Server URL for oTel sample application, use env variable as intended.
=> fix: use env variable for collector endpoint

apm-lambda-extension/Makefile
Publish the layer as a public layer
https://docs.aws.amazon.com/lambda/latest/dg/access-control-resource-based.html#permissions-resource-xaccountlayer
```bash
$ AWS_ACCESS_KEY_ID=*** \
AWS_SECRET_ACCESS_KEY=*** \
AWS_DEFAULT_REGION=us-west-2 \
ELASTIC_LAYER_NAME=v1v-aws-lambda-test \
make grant-public-layer-access
```
produced
```
$ cat .aws/.us-west-2-public
{
"Statement": "{\"Sid\":\"v1v-aws-lambda-test-x86_64\",\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":\"lambda:GetLayerVersion\",\"Resource\":\"arn:aws:lambda:us-west-2:267093732750:layer:v1v-aws-lambda-test:1\"}",
"RevisionId": "d42f1c13-4c4a-4384-9d59-f052d7ef35ef"
}
```
=> publish: make a layer public

.ci/create-arn-table.sh, apm-lambda-extension/Makefile
Add debug traces.
Fix issue in the CI when using `jq -r '.Version' <file>` which fails with
```
'parse error: Invalid numeric literal at line 1, column 5'
```
```
AWS_ACCESS_KEY_ID=\
AWS_SECRET_ACCESS_KEY=\
AWS_DEFAULT_REGION=us-west-2 \                
ELASTIC_LAYER_NAME=v1v-aws-lambda-test \            
make publish-in-all-aws-regions
publish 'v1v-aws-lambda-test-x86_64' in af-south-1
[debug] v1v-aws-lambda-test-x86_64 with version: 19
publish 'v1v-aws-lambda-test-x86_64' in eu-north-1
[debug] v1v-aws-lambda-test-x86_64 with version: 19
...
```
I cannot reproduce the error locally when parsing the json file with `jq`
```
[2022-02-04T12:27:07.386Z] publish 'elastic-apm-extension-ver0-0-3-arm64' in af-south-1
[2022-02-04T12:27:14.485Z] make[1]: Entering directory …
```
=> fix layer-name when granting public access and get ARN version 

docs/aws-lambda-extension.asciidoc
[Doc Preview ](https://github.com/elastic/apm-aws-lambda/blob/ee2fa9f8efa5439217675404af6b94984a38e7e3/docs/aws-lambda-extension.asciidoc)
=> Update docs describing the simplified onboarding for the extension.

apm-lambda-extension/extension/route_handlers.go
This was *somewhat* helpful when digging into https://github.com/elastic/apm-agent-nodejs/issues/2575
E.g.:
```
...
opbeans-lambda_1  | 2022/02/16 17:48:11 Could not read agent intake request body: unexpected EOF
...
```
=> Log the error when reading the intake req body fails

apm-lambda-extension/main.go
Use the WaitGroup to block the extension `for` loop iteration from completing until the go routine sending to the apm server has returned.
Resolves #128
=> Use WaitGroup to block extension loop iteration until apm server request is complete

apm-lambda-extension/extension/apm_server.go, apm-lambda-extension/extension/client.go, apm-lambda-extension/extension/client_test.go, apm-lambda-extension/extension/http_server_test.go, apm-lambda-extension/extension/route_handlers.go, apm-lambda-extension/main.go
This PR addresses some comments from this code review: https://github.com/elastic/apm-aws-lambda/issues/124#issuecomment-1042104258
Todo (3 March)
=> Address partial list of code review comments

apm-lambda-extension/Makefile
af-south-1 doesn't support `compatible-architectures`. 
We encountered this error before so removed it in https://github.com/elastic/apm-aws-lambda/pull/112
But then we erroneously added it back in https://github.com/elastic/apm-aws-lambda/issues/141
We then get this error when trying to publish the ARNs `CompatibleArchitectures are not supported in af-south-1.`
This PR removes the `compatible-architectures` option again.
=> Re-remove compatible-architectures setting as it's not supported in af-south-1

docs/aws-lambda-extension.asciidoc
Updates the docs to point users at the Node Agents layer.
=> doc: update node.js docs to mention layers

apm-lambda-extension/extension/apm_server.go, apm-lambda-extension/extension/process_env.go, apm-lambda-extension/extension/route_handlers.go, apm-lambda-extension/main.go
Following the merge PR #147, trailing newlines in log messages are no longer necessary. This pull request resolves issue #149.
=> Remove trailing newlines from log messages

apm-lambda-extension/extension/route_handlers.go
This pull request aims to implement the changes suggested as part of the high-level code review performed in #124. It replaces the manual forwarding of the APM agent's request for APM server info by a reverse proxy-based implementation. Go's [ReverseProxy](https://pkg.go.dev/net/http/httputil#ReverseProxy) implements the desired behavior out of the box.
Resolves #138
This PR passes all pre-existing unit-tests. 
Testing on a real Lambda function with the Python agent also shows that APM server info is successfully fetched :
```
x-amd64	State: Ready	Events: [INVOKE,SHUTDOWN]
{"@timestamp":"2022-03-22T12:16:46.559Z","ecs.version":"1.6.0","event.dataset":"apm-lambda-extension","log.level":"debug","message":"Received event."}
{"@timestamp":"2022-03-22T12:16:46.559Z","ecs.version":"1.6.0","event …
```
=> Retrieve APM Server info with a reverse proxy

docs/monitoring-aws-lambda.asciidoc
We're updating the documentation URL and anchors in https://github.com/elastic/apm-aws-lambda/pull/158. As a prerequisite, we need to update the file name and apm-server include statement so that the PR doc build can complete.
=> Duplicate documentation

docs/monitoring-aws-lambda.asciidoc
This will backport the following commits from `main` to `8.1`:
- [docs: duplicate file (#160)](https://github.com/elastic/apm-aws-lambda/pull/160)
=> [8.1] docs: duplicate file (#160)

apm-lambda-extension/extension/apm_server.go, apm-lambda-extension/extension/http_server.go, apm-lambda-extension/extension/process_env.go, apm-lambda-extension/extension/process_events.go, apm-lambda-extension/logsapi/client.go, apm-lambda-extension/logsapi/subscribe.go
=> Improve go docs

docs/lambda-selector/lambda-attributes-selector.asciidoc
=> Created fallback docs if GitHub API request fails.

docs/add-extension/add-extension-layer.asciidoc, docs/lambda-selector/lambda-attributes-selector.asciidoc, docs/monitoring-aws-lambda.asciidoc
This PR backports the following commits:
* https://github.com/elastic/apm-aws-lambda/pull/158
* https://github.com/elastic/apm-aws-lambda/pull/173
* d0f03e72b9e5d467dd375a60fc8ef98a1d34b29c (typo fix)
=> [8.1] Backport AWS Lambda doc updates

.ci/Jenkinsfile, apm-lambda-extension/go.mod
The goal of this pull request is to bump the minimum Go version supported by the extension codebase to 1.17. This bump has the following perks:
- Alignment with the [APM Server](https://github.com/elastic/apm-server/blob/main/go.mod)
- Resolve #163, tied to the `check-licenses`, `update-licenses` and `lint` make targets. These targets rely on the use of `go install` outside of a module-aware context, which is only fully [possible](https://maelvls.dev/go111module-everywhere/#go-run-knows-about-version-finally) as of Go 1.17.
- Ease the implementation of the metrics, as `Unix.Milliseconds()` and `Unix.Microseconds()` are only available in Go 1.17 (see commits 577e296 and c8e23cb).
This PR aims to track the discussion / changes necessary to perform the bump. The `.Jenkinsfile` and `go.mod` …
=> Bump minimum supported Go version to 1.17

apm-lambda-extension/main_test.go
While the addition of unit tests for `main.go` have been very useful to implement the backoff mechanism (#148) and assess the behaviour of the extension in several edge cases (#136), reliance on package-scoped state variables such as `ApmServerTransportState` induces hard-to-detect race conditions. 
An example is the commit c6b3fb5, whose CI pipeline failed due to a [race](https://apm-ci.elastic.co/job/library/job/apm-aws-lambda-mbp/job/main/78/console) between the goroutine tasked with setting the `ApmServerTransportState` back to `pending` and the start of `TestFullChannel`. The latter started before the goroutine completed its execution, and none of the events that we supposed to be queued during the test were sent to the APM Server. The issue did not appear in the many …
=> Structure main_test using the Testify Suite package

apm-lambda-extension/main.go
Resolves #187 by implementing the suggested behavior.
=> Stop queueing back data chunks after transport failures

apm-lambda-extension/extension/route_handlers.go
The goal of this hotfix to correct a regression introduced by #182.
`http.defaultTransport` was used as is and not cloned, which caused segmentation violations during final tests.
=> Clone Default Transport to configure info request reverse proxy

.ci/Jenkinsfile, .ci/push_docker.sh, apm-lambda-extension/Dockerfile, apm-lambda-extension/Makefile
=> Added building and pushing docker image for the lambda-extension

apm-lambda-extension/Makefile
The extensions directory must only contain executable extensions.
Add NOTICE.txt and dependencies.asciidoc to the top level of the
zip, rather than in the extensions directory.
=> Only add executable to extensions/

docs/add-extension/add-extension-layer-widget.asciidoc, docs/add-extension/add-extension-layer.asciidoc, docs/lambda-selector/lambda-attributes-selector.asciidoc
Agent docs depending on this change:
- https://github.com/elastic/apm-agent-java/pull/2658
- https://github.com/elastic/apm-agent-python/pull/1565
- https://github.com/elastic/apm-agent-nodejs/pull/2747
=> Add container image tab to lambda docs

docs/add-extension/add-extension-layer-widget.asciidoc, docs/add-extension/add-extension-layer.asciidoc, docs/lambda-selector/lambda-attributes-selector.asciidoc
This will backport the following commits from `main` to `8.2`:
- [Add container image tab to lambda docs (#204)](https://github.com/elastic/apm-aws-lambda/pull/204)
=> [8.2] Add container image tab to lambda docs (#204)

docs/add-extension/add-extension-layer-widget.asciidoc, docs/add-extension/add-extension-layer.asciidoc, docs/lambda-selector/lambda-attributes-selector.asciidoc
This will backport the following commits from `main` to `8.3`:
- [Add container image tab to lambda docs (#204)](https://github.com/elastic/apm-aws-lambda/pull/204)
=> [8.3] Add container image tab to lambda docs (#204)

README.md, apm-lambda-extension/DEVELOPMENT.md, apm-lambda-extension/e2e-testing/README.md, docs/add-extension/add-extension-layer.asciidoc, docs/monitoring-aws-lambda.asciidoc
This will backport the following commits from `main` to `8.3`:
- [docs: consistent naming (#226)](https://github.com/elastic/apm-aws-lambda/pull/226)
=> [8.3] docs: consistent naming (#226)

apm-lambda-extension/scripts/notice.sh
Go 1.17 added a new syntax for 'go run' to execute specific
versions without installing the binary.
See See https://tip.golang.org/doc/go1.17#go%20run
Remove the tempdir creation and removal and cleanup the notice
script.
=> refactor: avoid tempdir workaround in notice script

apm-lambda-extension/logsapi/process_metrics.go
Avoid sending empty metrics data and return the marshal error
instead of ignoring it.
The caller logs the error with the appropriate log level.
=> fix: do not ignore marshal errors when handling Report log event

apm-lambda-extension/extension/apm_server_transport.go, apm-lambda-extension/extension/apm_server_transport_test.go
The intake route of the APM server sends a 202 status accepted
if the request succeeds.
See https://github.com/elastic/apm-server/blob/main/docs/api-events.asciidoc#response
If auth fails the server returns a 401.
See https://github.com/elastic/apm-server/blob/3cd1a63bf218ea0ab0f240924236823e1815882b/beater/middleware/auth_middleware.go#L54-L57 and https://github.com/elastic/apm-server/blob/3cd1a63bf218ea0ab0f240924236823e1815882b/beater/request/result.go#L86
Related to https://github.com/elastic/apm-aws-lambda/issues/205+
=> feat: log a warning when authentication with APM server fails 

apm-lambda-extension/extension/http_server.go, apm-lambda-extension/logsapi/subscribe.go
Logs API server: the server was ignoring ErrServerClosed and logging an error.
APM Data server: the server was using an equality check with the error message but
it was never satisfied because of a typo ('server closed' vs 'Server closed'), leading
to an error message.
Both servers are now handling the error and logging a message that the server stopped
successfully. The code is using go 1.13 errors to avoid comparing strings and for better
compatibility.
=> fix: properly handle http.ErrServerClosed

apm-lambda-extension/main.go
NotifyContext was added in Go 1.16 and it also takes care of
unregistering the signal behaviour once done.
See https://go.dev/doc/go1.16#os/signal
=> refactor: replace signal handling with NotifyContext

apm-lambda-extension/extension/client_test.go, apm-lambda-extension/extension/http_server_test.go, apm-lambda-extension/go.mod, apm-lambda-extension/go.sum
Some old tests were using gotest.tools but most of them seem
to use testify.
=> refactor: use testify consistently

apm-lambda-extension/NOTICE.txt, apm-lambda-extension/extension/process_metadata.go, apm-lambda-extension/go.mod, apm-lambda-extension/logsapi/client.go, apm-lambda-extension/logsapi/subscribe.go
Go 1.13 added native errors with support for error wrapping
and additional information.
See https://go.dev/blog/go1.13-errors
=> refactor: replace pkg/errors with native go errors

apm-lambda-extension/Makefile, apm-lambda-extension/build.sh
Add support for SOURCE_DATE_EPOCH to avoid timestamp and timezones
issues.
See https://reproducible-builds.org/specs/source-date-epoch/
Make sure zip entries have a consistent mtime and strip extra
attributes.
See https://reproducible-builds.org/docs/archives/
Zip archives are now reproducible by default. Update script
to use the make task and avoid calling zip directly.
For more information see https://reproducible-builds.org/
=> feat: add support for reproducible builds

apm-lambda-extension/apmproxy/apmserver.go
metadata processing errors were being logged and ignored
leading a nil metadata.
=> fix: propagate and handle metadata errors

apm-lambda-extension/app/run.go
Do not call fatal or panic directly, instead propagate the error
to avoid multiple point of failure.
=> fix: handle main loop errors correctly

apm-lambda-extension/apmproxy/apmserver.go
Return an error if we failed to compress data to buffer
when posting to the apm server.
=> fix: do not send broken compressed data to apm server

apm-lambda-extension/apmproxy/receiver.go
http transports should be reused as per documentation. Recreating the
reverse proxy and the transport on each request is also preventing
connection resuse.
=> fix: stop recreating http transports on each info request

apm-lambda-extension/extension/client.go
Wrap error with contextual message for clarify and
to improve debugging.
=> refactor: improve extension client error messages

.ci/Jenkinsfile, apm-lambda-extension/apmproxy/metadata.go, apm-lambda-extension/apmproxy/metadata_test.go
Avoid copying byte slices and make ProcessMetadata zero-allocation.
Add a benchmark to reproduce the numbers:
```
name                       old time/op    new time/op    delta
ProcessMetadata/simple-16    7.89µs ± 8%    0.04µs ± 3%   -99.52%  (p=0.000 n=10+10)
name                       old alloc/op   new alloc/op   delta
ProcessMetadata/simple-16    12.6kB ± 0%     0.0kB       -100.00%  (p=0.000 n=10+10)
name                       old allocs/op  new allocs/op  delta
ProcessMetadata/simple-16      5.00 ± 0%      0.00       -100.00%  (p=0.000 n=10+10)
```
=> perf: improve processmetadata performance and reduce allocations

apm-lambda-extension/e2e-testing/e2e_test.go, apm-lambda-extension/e2e-testing/e2e_util.go, apm-lambda-extension/extension/client_test.go, apm-lambda-extension/extension/logger_test.go, apm-lambda-extension/main_test.go
io/ioutil was deprecated in Go 1.16.
See https://tip.golang.org/doc/go1.16#ioutil
This is needed to support newer version of golangci-lint because
the linters are flagging the usage of io/ioutil as an issue.
Because CI is using the linter for the lint job this is blocking
the update to newer version of go.
=> refactor: remove deprecated ioutil references

apm-lambda-extension/apmproxy/metadata.go
From the documentation:
> It is the caller's responsibility to call Close on the ReadCloser when done.
Should only affect compressed requests.
=> fix: close the compressed readers after processing metadata

.ci/Jenkinsfile, apm-lambda-extension/Makefile, apm-lambda-extension/go.mod
Bump the go version in go.mod to 1.19 and bump
golangci-lint version to support newer versions of go.
=> build: bump go version

apm-lambda-extension/CHANGELOG.asciidoc
This PR updates the Elastic APM AWS Lambda extension release notes.
* For https://github.com/elastic/apm-aws-lambda/issues/268.
=> docs: update release notes for APM Guide

apm-lambda-extension/apmproxy/client.go, apm-lambda-extension/apmproxy/option.go, apm-lambda-extension/apmproxy/receiver.go
The apmproxy client was using the timeout from the defaulttransport
instead of the user provided one.
Remove unused functional option and make the timeout configuration
more robust.
=> fix: use the correct timeout for the apmproxy client

.ci/Jenkinsfile, apm-lambda-extension/Makefile
Use Make targets, so CI behaves more like developer environments. This ensures license headers are checked in PRs.
Also, tidy up the Makefile a little:
- `zip` now depends on `build`. This ensures a `make zip` in isolation won't zip a stale build and confuse unsuspecting people like me.
- replace `gen-notice` with a non-PHONY `NOTICE.txt` target, by depending on go.mod
=> ci: use make in PRs

apm-lambda-extension/Makefile
The zip task was relying on 'touch -d @seconds' to set the timestamp of
output files to allow reproducible builds.
'touch -d @seconds' is not POSIX compliant and the standard only supports
a subset of formats:
https://man7.org/linux/man-pages/man1/touch.1p.html
The standard way of doing it would be to use one of those format or just use
'touch -t TIME'.
Since SOURCE_DATE_EPOCH is providing seconds since epoch and we don't have a
standard way to convert them to a standard format used by touch, we rely on
'date' and use a fallback mechanism to try two different syntax:
- Busybox and GNU coreutils date
- BSD date
=> fix: make zip task compatible with other systems

apm-lambda-extension/app/app.go, apm-lambda-extension/app/config.go, apm-lambda-extension/main_test.go
main_test was disabled after the global state for the logsapi
listener was removed.
The new approach is to choose a random port and pass the address
to the app.
Add a timeout to make sure tests don't hang.
Blocked by https://github.com/elastic/apm-aws-lambda/issues/249
Closes https://github.com/elastic/apm-aws-lambda/issues/249
=> test: reenable main tests

main_test.go
main tests were previously using 5s timeout but that leads to flaky tests
because the extension uses contexts with 5s delay to shutdown the logapi
and the receiver.
Timeouts are hardcoded and there's no way to change them as of now so the
immediate solution is to increase the test timeout.
=> test: bump main test timeout to 20s

docs/monitoring-aws-lambda.asciidoc
This will backport the following commits from `main` to `8.3`:
- [Added performance impact section to the docs (#279)](https://github.com/elastic/apm-aws-lambda/pull/279)
=> [8.3] Added performance impact section to the docs (#279)

docs/monitoring-aws-lambda.asciidoc
This will backport the following commits from `main` to `8.4`:
- [Added performance impact section to the docs (#279)](https://github.com/elastic/apm-aws-lambda/pull/279)
=> [8.4] Added performance impact section to the docs (#279)

CHANGELOG.asciidoc
Add a few changes that I think are worth mentioning before the release
=> changelog: add missing entries

README.md, TESTING.md
Fix bug report URL and update setup instructions.
Closes https://github.com/elastic/apm-aws-lambda/issues/241
=> docs: update README.md on current status and setup instructions for the project

Makefile
Code was moved to the root folder and ci scripts path in Makefile
needs to be updated to reflect the change.
=> ci: fix release scripts path

CHANGELOG.asciidoc, Makefile
build the extension with cgo disabled, to ensure there are
no glibc/ABI compatibility issues between the build host and
the target Lambda execution environment.
Closes https://github.com/elastic/apm-aws-lambda/issues/290
=> feat: disable cgo

app/run.go, extension/client.go
Read shutdownReason from the API and log it when exiting
=> feat: add support for shutdown reasons

CHANGELOG.asciidoc, logsapi/event.go, logsapi/metrics.go, logsapi/metrics_test.go, testdata/function/index.js
Makes a copy of the metadata to process log event in order to avoid corruption.
Fixes: #308
=> Copy metadata to avoid corruption

tf/.gitignore
smoke tests are creating build folder and log files.
Add them to gitignore
=> build: add smoke test log and build folder to gitignore

Makefile
license task is reporting missing licenses in the .terraform cache folder.
=> build: exclude terraform folder from license check

tf/output.tf, tf/test.sh
Configurable regions are supported by the terraform script bu the bash script used for smoke testing is only invoking the lambda function in the default region (eu-central-1).
Add a new output variable to retrieve the aws region in the shell script and update the lambda invocation.
=> test: fix smoke test script invoking function on the wrong region

tf/main.tf, tf/variables.tf
The terraform script used for smoke testing was defaulting to the latest version of ess.
Because we want to test on stable versions and allow people to reuse the script to provision and test the dev environment, add a variable to make ess version configurable and default to the latest 8.x version.
=> build: make ess version configurable

docs/monitoring-aws-lambda.asciidoc
A new, standalone documentation book exists for the APM AWS Lambda extension. This PR fixes the formatting of the book as it no longer follows the formatting of the APM Guide. See the new docs [here](https://www.elastic.co/guide/en/apm/lambda/current/index.html) (before the fixes in this PR).
* For https://github.com/elastic/observability-docs/issues/2207.
=> docs: fix layout in new book

.ci/jobs/apm-aws-lambda-smoketests-mbp.yml
Companion PR to https://github.com/elastic/apm-aws-lambda/pull/310
Add job definition
=> ci: add smoke testing job definition

.gitignore, docs/index.asciidoc, docs/monitoring-aws-lambda.asciidoc, docs/release-notes.asciidoc
* Closes https://github.com/elastic/apm-aws-lambda/issues/268.
~Adds an end-of-life table to the documentation~
~* Closes https://github.com/elastic/apm-aws-lambda/issues/263.~
~Dates reflect Elastic's new EOL policy effective Oct 1, 2022.~
=> docs: add release notes to docs

apmproxy/apmserver.go, apmproxy/apmserver_test.go, apmproxy/batch.go, apmproxy/batch_test.go, apmproxy/client.go, app/run.go, logsapi/event.go, logsapi/functionlogs.go, logsapi/functionlogs_test.go, logsapi/metrics.go, logsapi/metrics_test.go
Currently, the package `apmproxy` is required by the package `logsapi` due to the abuse of `APMData` struct. The PR refactors the struct so that it's usage is contained within `apmproxy`.
Part of #315
=> Remove usage of APMData within logsapi

.ci/Jenkinsfile, Makefile
Ensure the lambda is always pointing to the version 1.
Version and releases will be predictable. 
@AlexanderWert provided some feedback in the past:
> One think that I observed is, that it would be nice and less confusion for the users if all the Layers we are publishing would always have version 1 as the layer version. (Sometimes it's not, when something fails and we retrigger publishing).
Do you think we could add a layer deletion step (if a layer with a certain name already exists) before we do the publishing? In this way we could guarantee that the layer ARNs always have the suffix / version 1
I think this would improve experience a lot, since we then won't need to link to the GitHub table but could provide a generic pattern and maybe even writing a small HTML / Javascript tool …
=> release: delete layer before publishing

CHANGELOG.asciidoc, RELEASE.md, extension/version.go
- Update version
- Update changelog, add missing entries
- Remove step about updating EOL from RELEASE.md, as EOL info is now centralised
=> Prepare v1.2.0

accumulator/batch.go, accumulator/batch_test.go, accumulator/invocation.go, accumulator/invocation_test.go, apmproxy/apmserver.go, apmproxy/apmserver_test.go, apmproxy/receiver.go, app/run.go, logsapi/client.go, logsapi/event.go
- Transaction registration can happen before the invocation is registered. Handle such cases by keeping the payload of transaction registration in a cache and handling it when the invocation is registered.
- Transaction registration will not have the duration of the transaction or if it does have it, the value will be a default value. We attempt to calculate the transaction duration based on the invocation timestamp, function deadline(for timeouts), OR `runtimeDone` log timestamp for agent issues.
- Increases the timeout for the deadline of extension from 100ms to 200ms.
Related to https://github.com/elastic/apm-agent-go/issues/1323
=> Handle txn registration if invocation registration is late

testing/Makefile, testing/benchmarking/README.md, testing/benchmarking/main.tf, testing/benchmarking/variables.tf, testing/tf-modules/lambda_deployment/README.md, testing/tf-modules/lambda_deployment/main.tf, testing/tf-modules/lambda_deployment/variables.tf
The PR exposes stack version to `make` commands and adds support for setting lambda memory size as well as specifying custom lambda extension (by default we were building the current code and deploying it). With these changes we can test lambda functions with any version of the extension.
=> Expose more options for the benchmarking tf module

CHANGELOG.asciidoc, apmproxy/receiver.go, app/run.go, logsapi/event.go
`platform.report` metrics for a lambda invocation are reported in the future invocation (in most cases the next one). Due to this, we will not have the report metrics for the last invocation till shutdown, and, as per the behavior of the extension prior to this PR, we will end up dropping the last metric. For periodic (hourly/daily/weekly) invocations, this will lead to no `platform.report` metric.
During shutdown the extension gets a deadline of 2 seconds, this PR uses some of the 2 seconds to wait for the logs API to send us the` platform.report` metric for the last seen invocation. This wait is executed for each execution env/instance that served an invocation (NOT for each invocation). Per our initial benchmarks, the wait lasts for a maximum of 40ms (avg: ~5ms).
While the PR fixes the …
=> On shutdown wait for lambda logs API to report the final platform report metrics

testing/benchmarking/main.tf, testing/functions/python3.8/main.py, testing/tf-modules/lambda_deployment/main.tf, testing/tf-modules/lambda_deployment/variables.tf
- Adds support for cloudwatch logging for the lambda functions
- Fixes handling of bool variable in headers for the python lambda function
- Fixes the lambda extn layer handling to trigger an update on change of extension code
- Refactors the `lambda_deployment` module to have clear boundaries (should only handle deployment of a provided zip package)
=> Enable cloudwatch logging for lambda deployment tf and other minor fixes

apmproxy/receiver.go, apmproxy/receiver_test.go
When proxying info requests to apm server we're loggin an error if the server is unreachable.
The ErrorHandler should also write a status code back to avoid returning a Status 200.
Add ModifyResponse to log a debug message with the body on unexpected responses and let the ErrorHandler proxy the status code back to the agent.
A StatusBadGateway is returned for generic errors.
=> fix: do not return status 200 on server info request when unreachable

testing/functions/go1.x/build.sh
Disable cgo in go test function to ensure there are no glibc/ABI compatibility issues between the build host and the target Lambda execution environment.
Similar to https://github.com/elastic/apm-aws-lambda/pull/292
Discovered while testing https://github.com/elastic/apm-aws-lambda/pull/347
```
/var/task/main: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /var/task/main)
/var/task/main: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /var/task/main)
```
=> test: disable cgo in go test function

NOTICE.txt
It's 2023 :tada: 
CI is failing because the year is not up to date.
=> build: update notice to 2023

CHANGELOG.asciidoc, accumulator/batch.go, accumulator/invocation.go, accumulator/invocation_test.go, app/run.go, logsapi/client.go, logsapi/event.go, logsapi/metrics.go, logsapi/metrics_test.go
The current extension will drop the `platform.report` logs if the platform report metrics are reported in an invocation that does not immediately succeed in the invocation generating the platform report. To prevent the logs from getting dropped the PR does the following changes:
1. Updates the lifecycle of the cached invocation data to be cleared on receiving `platform.report` metric for its corresponding request ID.
2. Query the cached invocation data instead of using the previous event and drop the log event if the prev event doesn't match the event's request ID.
Part of #334
=> Process platform report metrics when extn is lagging

Makefile
Binary size went from 11MB to 7.4MB
Closes https://github.com/elastic/apm-aws-lambda/issues/291
=> build: strip debugging information from final binary 

apmproxy/receiver_test.go
This is to avoid issues in CI with ipv6
Unblock https://github.com/elastic/apm-aws-lambda/pull/362
=> test: use 127.0.0.1 explicitly instead of resolving localhost

docs/monitoring-aws-lambda.asciidoc
Updates lambda config options:
* Moves deprecated options to the bottom of the list
* Cleans up deprecation text
* Adds `ELASTIC_APM_LAMBDA_CAPTURE_LOGS`
Closes https://github.com/elastic/apm-aws-lambda/issues/323.
=> docs: update lambda config

docs/monitoring-aws-lambda.asciidoc
This will backport the following commits from `main` to `8.6`:
- [docs: update lambda config (#365)](https://github.com/elastic/apm-aws-lambda/pull/365)
=> [8.6] docs: update lambda config (#365)

CHANGELOG.asciidoc, RELEASE.md, extension/version.go
=> Prepare release for v1.3.0

.goreleaser.yaml
AWS_SESSION_TOKEN and AWS_SECURITY_TOKEN are only needed when using tools like aws-vault. But in the workflow we only have "standard" credentials.
=> Fix release workflow

apmproxy/apmserver.go
Related to the latest lambda SDH: we are missing some visibility on error responses.
If decoding fails or the error is using another format there are no logs, losing potential information and visibility.
=> feat: print response body on error if decoding fails

CHANGELOG.asciidoc, accumulator/batch.go, accumulator/batch_test.go, apmproxy/receiver.go
The PR updates the `/register/transaction` endpoint to accept `NDJSON`. The `/register/transaction` endpoint can now accept `metadata` as the first event in `NDJSON` body and cache it for future calls. A complete list of changes introduced in the PR is as follows:
1. Change the `Content-Type` for the `/register/transaction` endpoint from `application/vnd.elastic.apm.transaction+json` to `application/vnd.elastic.apm.transaction+ndjson`.
2. Add support for `deflate` and `gzip` content encoding for the `/register/transaction` endpoint.
3. Allow `metadata` as the first event in the `NDJSON` body to the `/register/transaction` endpoint. The `metadata` is cached and used to send data to APM-Server. The cached metadata is NOT updated by the metadata sent via the intake endpoint.
Closes #352
=> Allow metadata in register transaction

accumulator/batch.go, accumulator/invocation.go, accumulator/invocation_test.go
Renames `CreateProxyTxn` to `MaybeCreateProxyTxn` as it better represents what the function does. A proxy transaction will be created only if it is needed. A proxy transaction will be needed if:
1. A transaction with the same `transaction.id` as the one registered during agent init is not reported by the agent.
2. An invocation has already been finalized before.
3. Transaction hasn't been successfully registered during agent init.
=> Rename CreateProxyTxn to MaybeCreateProxyTxn

CHANGELOG.asciidoc, extension/version.go
Release lambda extension `v1.4.0` with updated register transaction method.
=> Prepare for v1.4.0 release

.gitignore, tf/main.tf
Slightly related to https://github.com/elastic/apm-aws-lambda/issues/389
Debugging and reproducing the issue was a pain. This PR improves the smoke test to use the AWS secret manager instead of passing the secret token directly.
This should have more coverage and make it easier for developer to reproduce issues with the secrets manager.
The third-party terraform-aws-modules provider has also been removed in favour of the "official" aws provider.
=> test: use AWS Secrets manager in smoke test

apmproxy/receiver.go, apmproxy/receiver_test.go
Forward auth headers for info requests. This does not affect data ingestion as we are already forwarding the headers there.
A test has been added to ensure the auth options passed to the lambda extension are correctly forwarded.
Closes https://github.com/elastic/apm-aws-lambda/issues/389
=> fix: send auth headers with info requests if missing

CHANGELOG.asciidoc, app/aws.go
If there is an error retrieving an APM auth secret from AWS Secrets
Manager (attempted when ELASTIC_APM_SECRETS_MANAGER_API_KEY_ID or ELASTIC_APM_SECRETS_MANAGER_SECRET_TOKEN_ID
are provided), then the extension will now *log a warning* rather
than erroring out.
This allows the Lambda function to still work. Only the reporting of
APM server data will fail (with a 403). This was already the behavior
for an invalid ELASTIC_APM_SECRET_TOKEN.
I configured a Lambda fn, `trentm-play-fn1`, to use the current latest extension and Node.js APM layers. I configured a bogus secret ID for a secret token:
```
ELASTIC_APM_SECRETS_MANAGER_SECRET_TOKEN_ID=bogus-no-such-secret
```
then I invoked the function (via its Lambda URL). It fails:
```
% curl -i https://[REDACTED].lambda-url.us-west-2.on.aws/ …
```
=> fix: gracefully handle an error retrieving auth info from AWS Secrets Manager

docs/monitoring-aws-lambda.asciidoc
I'm not sure that what I'm writing here is correct. Can someone please double-check? This PR is based on the information explained in https://github.com/elastic/apm-aws-lambda/issues/349.
Tagging @lahsivjar and @kruskall for review as you're the last two people to touch this file. Please feel free to ping others if you're not the correct reviewers.
* Closes https://github.com/elastic/apm-aws-lambda/issues/349.
If this PR is correct and can be merged, I'll manually backport the changes to 8.10 and 8.9.
=> Agent-server comm options are not applicable to AWS lambda extension

docs/lambda-selector/lambda-attributes-selector.asciidoc
This will backport the following commits from `main` to `8.9`:
- [docs: use the 'latest' GH release API for the latest extension or agent release (#402)](https://github.com/elastic/apm-aws-lambda/pull/402)
=> [8.9] docs: use the 'latest' GH release API for the latest extension or agent release (#402)

docs/lambda-selector/lambda-attributes-selector.asciidoc
This will backport the following commits from `main` to `8.10`:
- [docs: use the 'latest' GH release API for the latest extension or agent release (#402)](https://github.com/elastic/apm-aws-lambda/pull/402)
=> [8.10] docs: use the 'latest' GH release API for the latest extension or agent release (#402)

docs/monitoring-aws-lambda.asciidoc
This will backport the following commits from `main` to `8.9`:
- [Agent-server comm options are not applicable to AWS lambda extension (#403)](https://github.com/elastic/apm-aws-lambda/pull/403)
=> [8.9] Agent-server comm options are not applicable to AWS lambda extension (#403)

.github/workflows/README.md, .github/workflows/test-docs.yml, .github/workflows/test.yml
* Enable GitHub check to act as a Gatekeeper. Similarly done in some [other projects](https://github.com/elastic/apm-agent-ruby/pull/1378)
* Docs
* PRs with only docs will not run the whole CI workflow.
=> action: faster docs PRs and branch protection gatekeeper

CHANGELOG.asciidoc, app/run.go
=> Process shutdown event after flushing data

CHANGELOG.asciidoc
Adds changelog entry for `v1.5.1`. We were also missing changelog for the released version `v1.5.0`, the PR adds that.
=> Update CHANGELOG for v1.5.1 release

.github/workflows/smoke-tests.yml, tf/cleanup.sh, tf/test.sh
`cleanup.sh` didn't exist so it didn't get triggered automatically and the trap uses some env variable to skip the destroy
=> ci: force tearing down the infrastructure

.github/workflows/smoke-tests.yml
The secrets was deprecated a few months ago and is no longer updated, and the key was deleted.
=> fix: use the correct secret

.github/workflows/addToAPMProject.yml, .github/workflows/addToDocsProject.yml, .github/workflows/labeler.yml, .github/workflows/test-reporter.yml
⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
We want to set the default permissions for workflows to read-only for contents. 
This is a security measure to prevent accidental changes to the repository.
This change adds a top-level permissions block to all workflows in the .github/workflows directory.
```yaml
permissions:
contents: read
```
In some cases workflows might need more permissions than just `contents: read`.
Please checkout this branch and add the necessary permissions to the workflows.
If your workflow uses a Personal Access Token (PAT), we can still add the permissions block,
but it will not have any effect.
Merging this PR as is might cause workflows that need more permissions to fail.
If there are any questions, please reach out to …
=> security: add permissions block to workflows

.ci/release-github.sh
* Upload `checksums.txt` when a release.
* That's the file generated when running the `goreleaser`.
* Upload `sbom` when a release:
* That's the fine generated when running the `goreleaser`.
```bash
$ ls -1 dist/
artifacts.json
config.yaml
metadata.json
v0.0.0-linux-amd64.zip
v0.0.0-linux-amd64.zip.sbom
v0.0.0-linux-arm64.zip
v0.0.0-linux-arm64.zip.sbom
```
https://goreleaser.com/customization/checksum/\?query\=checksums
=> release: store checksums and sbom

.github/actions/bootstrap/action.yml, .github/dependabot.yml, .github/workflows/dependabot-pr.yml, .github/workflows/release.yml, .github/workflows/smoke-tests.yml, .github/workflows/test.yml
Fixes a regression when enabled the `goreleaser` with sbom. The smoke-tests uses `goreleaser` and I didn't detect it in https://github.com/elastic/apm-aws-lambda/blob/62236d32ae7613a4f82fefff471b09e4b1e1aca0/Makefile#L72
I refactored the code to use a composite action to reuse the same steps in the different GitHub workflows
=> github-action: use composite action and fix smoke-tests

.github/workflows/test.yml
The GitHub token scope is not passed when running on forked repositories
=> github-action: remove provenance for forked

.github/workflows/release.yml
If a github release exists, then it fails. Avoid rerunning the workflow since AWS lambdas are immutable and their versions are bumped if created a new one.
This should avoid the [edge case](https://github.com/elastic/apm-aws-lambda/issues/462) that a GitHub workflow was triggered accidentally and remove the lambdas.
> github.ref_name	string	The short ref name of the branch or tag that triggered the workflow run. This value matches the branch or tag name shown on GitHub. For example, feature-branch-1.
For pull requests, the format is <pr_number>/merge.
=> github-action: avoid release if github release already exists

.github/workflows/release.yml, .github/workflows/smoke-tests.yml
Follow-up, support for Keyless.
=> ci(slack/docker): use github secrets

.github/workflows/release.yml, .github/workflows/smoke-tests.yml
Use GitHub secrets
There will be a follow-up to use keyless instead.
=> ci(github-secrets): aws lambda publish

.github/workflows/smoke-tests.yml, tf/main.tf
- use the observability-ci AWS account instead of elastic-observability
- use [elastic/oblt-actions/aws/auth@v1.10.0](https://github.com/elastic/oblt-actions/tree/v1.10.0/aws/auth) for authenticating keyless with OIDC to the default CI AWS account. 
tested in https://github.com/elastic/apm-aws-lambda/actions/runs/9646343492
=> Use keyless authentication for smoke tests

.github/workflows/smoke-tests.yml
`oblt-cli` is not using vault anymore. Let's use the correct secret storage
Running the smoke-tests using a test feature branch:
- https://github.com/elastic/apm-aws-lambda/actions/runs/9658938892/job/26641201571
=> ci: use secrets from the source of truth

.github/labeler-config.yml, .github/workflows/labeler.yml
Upstream github/issue-labeler meanwhile supports labelling PRs as well. Not using an outdated fork means removing technical debt.
=> Update issue and PR labeler

testing/smoketest/get_username.sh, testing/smoketest/locals.tf, testing/smoketest/main.tf, testing/smoketest/output.tf, testing/smoketest/variables.tf
The smoketest so far required manual input of the username, used as a tag for the AWS lambda environment.
This changes the smoketest to automatically use the GitHub username. The name is retrieved by either using the `gh` tool or, as a fallback, using `ssh`.
=> test: automatically use GitHub username

.github/workflows/labeler.yml
Automatically setting 'community' and 'triage' labels for issues and PRs now is disabled for members of the observability team.
=> ci: Check observability instead of apm team for issue/PR authors

.github/workflows/smoke-tests.yml, testing/smoketest/get_username.sh
This hopefully fixes the error from `gh` in the smoketest:
```
Program: ./get_username.sh
Error Message: gh: Resource not accessible by integration (HTTP 403)
```
=> test: Use automatically created GITHUB_TOKEN for smoketest

.github/workflows/smoke-tests.yml, testing/smoketest/main.tf, testing/smoketest/variables.tf
tear-down does not cleanup the `aws_cloudwatch_log_group`, I'd assume is because the retention policy is honoured.
Therefore, it's required to use an unique name, otherwise it will fail with:
```
Error: creating CloudWatch Logs Log Group (/aws/lambda/github-actions-smoke-testing-test): operation error CloudWatch Logs: CreateLogGroup, https response error StatusCode: 400, RequestID: 4161b73e-8b5b-4fef-8a17-64aa29c2cdd4, ResourceAlreadyExistsException: The specified log group already exists
with aws_cloudwatch_log_group.example,
on main.tf line 105, in resource "aws_cloudwatch_log_group" "example":
105: resource "aws_cloudwatch_log_group" "example" {
Error: creating IAM Policy (smoketest_extension_lambda_logging): operation error IAM: CreatePolicy, https response error StatusCode: 409, …
```
=> fix: use unique name to avoid issues when running in the CI

testing/benchmarking/main.tf, testing/benchmarking/variables.tf, testing/smoketest/main.tf
Honours the changes in https://github.com/elastic/apm-server/pull/13841
I could not find how the `testing/benchmarking` gets triggered, but I applied some changes to include the new var.
=> terraform: configure github workflow run id

testing/benchmarking/main.tf, testing/smoketest/main.tf
I accidentally used `vars` but it's not a valid name but `var` instead 👼 
https://github.com/elastic/apm-aws-lambda/actions/runs/10316386121 should validate this PR
=> tf: use singular var

e2e-testing/sam-nodejs/sam-testing-nodejs/package.json
An issue discovered in Axios 0.8.1 through 1.5.1 inadvertently reveals the confidential XSRF-TOKEN stored in cookies by including it in the HTTP header X-XSRF-TOKEN for every request made to any host allowing attackers to view sensitive information.
Affected versions: >= 0.8.1, < 0.28.0
=> Fix Axios Cross-Site Request Forgery Vulnerability

.github/workflows/addToAPMProject.yml, .github/workflows/addToDocsProject.yml, .github/workflows/labeler.yml
No more finer-grained tokens but ephemeral tokens using a GH app
=> github-actions: use ephemeral tokens for add the different projects board

.github/workflows/smoke-tests.yml
Similarly done in https://github.com/elastic/apm-server/pull/14323
=> ci(smoke-tests): read secrets for running the tear-down immediately after

accumulator/batch.go, accumulator/batch_test.go, apmproxy/apmserver.go, apmproxy/receiver.go
Initialize local variable only once and make sure expected APMData is handled first.
=> Avoid race conditions when handling data

.github/workflows/test.yml
⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
NOTE: https://github.com/elastic/apm-pipeline-library has been archived in favor of 
https://github.com/elastic/oblt-actions.
Requires https://github.com/elastic/oblt-actions/pull/16 to be merged.
If there are any questions, please reach out to the @elastic/observablt-ci
=> github-action: use elastic/oblt-actions/github/check-dependent-jobs

.github/workflows/release.yml, .github/workflows/smoke-tests.yml
we own oblt-actions and we are committed to keeping compatibility in `v1`
=> github-actions: use v1 alias

.golangci.yml, Makefile, e2e-testing/e2e_test.go, go.mod, logsapi/model/model_json.go, main_test.go
Go 1.22 has reached EOL.
We need to upgrade golangci-lint with it for compatibility reasons.
=> Upgrade go to 1.23 and golangci-lint to 1.64

docs/reference/aws-lambda-secrets-manager.md
Updates links to APM agent docs. The IDs they link to will be updated in:
* https://github.com/elastic/apm-agent-nodejs/pull/4479/commits/a6ed762b28e668d730e8c25486b22fb6d59f44ab
* https://github.com/elastic/apm-agent-java/pull/3981/commits/de7bc57c4e309cd9a7573eb2a01db18ec53195e1
* https://github.com/elastic/apm-agent-python/pull/2221/commits/e795df5d8275c4a7399b24546e83212c3c99a934
=> [docs] Update links to APM agent docs

docs/reference/aws-lambda-secrets-manager.md, docs/reference/index.md
Fix external links that incorrectly use `.md` instead of `.html`.
=> [docs] Fix external links

.github/workflows/smoke-tests.yml
Change the federation oidc for gcp on github actions and buildkite from `elastic-observability` to `elastic-observability-ci `since the support to create the Google Secrets for `elastic-cloud-observability-team-*` in the `elastic-observability-ci` has been added.
This is part of https://github.com/elastic/observability-robots/issues/2797
Replace the gcp account for oidc federation by `elastic-observability-ci`
The secrets in the CI are not aimed to be accessed by Developers.
=> Start using elastic-observability-ci google cloud project for ci secrets
